### PR TITLE
fixed unsafe code for absent keys

### PR DESCRIPTION
**Pull request by steph-mipt**
old version of code threw panic with absent keys

### CODE REVIEW

**Comment by steph-mipt** [comment]
i used old version without banderwagon, but I didn't find any active branches with that version

**Comment by kevaundray** [comment]
Hi, the master branch should be using banderwagon. We no longer support bandersnatch

**Comment by kevaundray** [comment]
Change looks good either way though :)

**Comment by steph-mipt** [comment]
Yeah, i understand. But currently i'm trying to work with condrieu test-net, so I have some issues with decoding proof with banderwagon :(

**Comment by steph-mipt** [comment]
Oh, sorry. Last commit is excess

**Comment by kevaundray** [comment]
> Yeah, i understand. But currently i'm trying to work with condrieu test-net, so I have some issues with decoding proof with banderwagon :(

The proof decoding is because Rust and Go disagree on the proof format, we have a few issues opened up for it

**Pull request closed without merging**
